# build-vdd.ps1 -- build VDD (MttVDD) from source with the recipe that is proven
#                   to produce loadable IddCx drivers on this machine.
#
# WHY
#   Step 1 of MODE4-PLAN.md. Mode 4 needs a remote-session IddCx driver, and
#   iddseat.dll does not load on any devnode type (three-way differential,
#   2026-08-17). VDD's shipped binary DOES load. So the route to mode 4 is VDD's
#   source plus the two remote-session flags -- but only if we can first
#   reproduce a loadable driver FROM SOURCE.
#
#   THE GATE: build unmodified, install, create with devgen, confirm Status OK.
#   If a from-source build does not load when the shipped binary does, something
#   in this recipe differs and every hour spent on remote-session flags after
#   that is wasted. Do not skip this.
#
#   VDD's own vcxproj cannot build here -- no WDK include paths, dies on
#   wudfwdm.h. build-mssample.ps1's paths work, so they are reused verbatim.
#
# USAGE (elevated, x64 Native Tools)
#   .\build-vdd.ps1                 # compile only
#   .\build-vdd.ps1 -Install        # + stamp, catalog, sign
#   .\build-vdd.ps1 -Install -Stage # + pnputil and devgen. THE GATE.

param(
    [string]$Src     = 'C:\Programs\vddsrc\Virtual-Display-Driver-25.7.23',
    [string]$OutDir  = 'C:\Programs\hydra\dist\vdd',
    [string]$KitRoot = 'C:\Program Files (x86)\Windows Kits\10',
    [string]$SdkVer  = '10.0.26100.0',
    [string]$IddCx   = '1.10',    # the only registered extension on this box:
                                 # Control\Wdf\UMDF\IddCx\Versions\1\2 -> Service = IddCx0102
    [string]$Umdf    = '2.33',
    [switch]$Install,
    [switch]$Stage
)

$ErrorActionPreference = 'Stop'

$drvDir = Join-Path $Src 'Virtual Display Driver (HDR)\MttVDD'
$cpp    = Join-Path $drvDir 'Driver.cpp'
$inf    = Join-Path $drvDir 'MttVDD.inf'
$common = Join-Path $Src 'Common\Include'

foreach ($p in @($cpp, $inf, $common)) {
    if (-not (Test-Path $p)) { throw "not found: $p" }
}
New-Item -ItemType Directory -Force -Path $OutDir | Out-Null

# --- includes -------------------------------------------------------------
# wudfwdm.h lives ONLY under Include\wdf\umdf\<ver>\ -- not Include\<sdk>\km,
# whatever build-driver.ps1's comment says. That is why VDD's vcxproj fails.
# winrt is needed for WRL (corewrappers.h); the sample needed it too.
$inc = @(
    "$KitRoot\Include\$SdkVer\um",
    "$KitRoot\Include\$SdkVer\shared",
    "$KitRoot\Include\$SdkVer\km",
    "$KitRoot\Include\$SdkVer\winrt",
    "$KitRoot\Include\$SdkVer\um\iddcx\$IddCx",
    "$KitRoot\Include\wdf\umdf\$Umdf",
    $common,
    $drvDir,
    'C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.44.35207\atlmfc\include'
)
foreach ($d in $inc) { if (-not (Test-Path $d)) { throw "missing include dir: $d" } }

$libs = @(
    "$KitRoot\Lib\$SdkVer\um\x64\iddcx\$IddCx\iddcxstub.lib",
    "$KitRoot\Lib\wdf\umdf\x64\$Umdf\WdfDriverStubUm.lib",
    "$KitRoot\Lib\$SdkVer\um\x64\d3d11.lib",
    "$KitRoot\Lib\$SdkVer\um\x64\dxgi.lib",
    "$KitRoot\Lib\$SdkVer\um\x64\avrt.lib",
    "$KitRoot\Lib\$SdkVer\um\x64\advapi32.lib",
    "$KitRoot\Lib\$SdkVer\um\x64\kernel32.lib",
    "$KitRoot\Lib\$SdkVer\um\x64\ole32.lib",
    "$KitRoot\Lib\$SdkVer\um\x64\oleaut32.lib",   # VDD parses XML via COM/MSXML
    "$KitRoot\Lib\$SdkVer\um\x64\shlwapi.lib"
)
$libs += (Get-ChildItem 'C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.44.35207\atlmfc\lib\x64' -Filter '*.lib' -EA SilentlyContinue | ForEach-Object FullName)
$libs += "$KitRoot\Lib\$SdkVer\ucrt\x64\ucrt.lib"
$ntdll = @("$KitRoot\Lib\wdf\umdf\x64\$Umdf\ntdllUm.lib",
           "$KitRoot\Lib\$SdkVer\um\x64\ntdll.lib") |
         Where-Object { Test-Path $_ } | Select-Object -First 1
if ($ntdll) { $libs += $ntdll }

$libs | Where-Object { -not (Test-Path $_) } | ForEach-Object { Write-Warning "lib not found: $_" }
$libs = $libs | Where-Object { Test-Path $_ }

Write-Host "kit paths OK (SDK $SdkVer, IddCx $IddCx, UMDF $Umdf); $($libs.Count) libs" -ForegroundColor Green

# --- WPP stub -------------------------------------------------------------
# Trace.h drives WPP, whose .tmh files are generated by tracewpp during a WDK
# MSBuild pass we are not running. No-op the macros and provide an empty .tmh.
# Same two obstacles the Microsoft sample hit.
$stub = Join-Path $OutDir 'wppstub.h'
@'
#pragma once
#define WPP_INIT_TRACING(a,b)
#define WPP_CLEANUP(a)
#define TraceEvents(...)
#define WPP_LEVEL_FLAGS_LOGGER(lvl,flags)
#define WPP_LEVEL_FLAGS_ENABLED(lvl,flags) (0)
#define WPP_LEVEL_LOGGER(lvl)
#define WPP_LEVEL_ENABLED(lvl) (0)
'@ | Set-Content $stub -Encoding ASCII

foreach ($t in @((Join-Path $drvDir 'Driver.tmh'))) {
    if (-not (Test-Path $t)) { New-Item -ItemType File -Force -Path $t | Out-Null }
}

# --- compile --------------------------------------------------------------
# NOTE: no /DWIN32_NO_STATUS. It suppresses the NTSTATUS constants in winnt.h
# that WRL's corewrappers.h needs, and the sample failed on STATUS_WAIT_0 until
# it was dropped. Our own driver never noticed because it does not use WRL.
$cldefs = @(
    '/D_UNICODE','/DUNICODE',
    '/D_WIN32_WINNT=0x0A00',
    '/DUMDF_USING_NTSTATUS',
    '/DNTDDI_VERSION=0x0A000010',
    '/DIDDCX_VERSION_MAJOR=1',
    '/DIDDCX_VERSION_MINOR=10',
    '/DIDDCX_MINIMUM_VERSION_REQUIRED=3'
)

$obj = Join-Path $OutDir 'Driver.obj'
$dll = Join-Path $OutDir 'MttVDD.dll'

Write-Host "compiling VDD Driver.cpp ..." -ForegroundColor Cyan
$compile = @('/nologo','/c','/EHsc','/std:c++17','/W3','/MT') + $cldefs +
           ($inc | ForEach-Object { "/I$_" }) +
           @("/FI$stub", $cpp, "/Fo:$obj")
$out = & cl.exe @compile 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "COMPILE FAILED:" -ForegroundColor Red
    $out | Where-Object { $_ -match ': (error|fatal error) ' } | Select-Object -First 25 |
           ForEach-Object { Write-Host "  $_" -ForegroundColor DarkRed }
    throw "compile stage failed"
}
Write-Host "  compiled OK" -ForegroundColor Green

Write-Host "linking MttVDD.dll ..." -ForegroundColor Cyan
$link = @('/nologo','/DLL',"/OUT:$dll",$obj) + $libs + @('/NODEFAULTLIB:kernel32.lib','/NODEFAULTLIB:libucrt.lib')
$out = & link.exe @link 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "LINK FAILED:" -ForegroundColor Red
    $out | Where-Object { $_ -match ': (error|fatal error|unresolved) ' } | Select-Object -First 25 |
           ForEach-Object { Write-Host "  $_" -ForegroundColor DarkRed }
    throw "link stage failed"
}
Write-Host "  linked OK" -ForegroundColor Green

Copy-Item $inf $OutDir -Force
Copy-Item (Join-Path (Split-Path $Src) 'vdd\VirtualDisplayDriver\vdd_settings.xml') $OutDir -Force -EA SilentlyContinue
$infOut = Join-Path $OutDir 'MttVDD.inf'
$t = [IO.File]::ReadAllText($infOut)
if ($t -match [regex]::Escape('$UMDFVERSION$')) {
    $t = $t -replace [regex]::Escape('$UMDFVERSION$'), "$Umdf.0"
    [IO.File]::WriteAllText($infOut, $t, (New-Object System.Text.UTF8Encoding $false))
}

Write-Host ""
Write-Host "Built: $dll  ($((Get-Item $dll).Length) bytes)" -ForegroundColor Green
Write-Host "  shipped MttVDD.dll is 251,640 -- a large difference is worth a look" -ForegroundColor DarkGray
Select-String -Path $infOut -Pattern 'UmdfExtensions|UmdfLibraryVersion|ServiceBinary|MyDevice_Install,' |
    ForEach-Object { Write-Host "  $($_.Line.Trim())" -ForegroundColor DarkGray }

if (-not $Install) { Write-Host "`nRe-run with -Install to stamp, catalog and sign." -ForegroundColor Cyan; return }

# --- stage ----------------------------------------------------------------
Write-Host ""
Write-Host "=== signing ===" -ForegroundColor Cyan
& "$KitRoot\bin\$SdkVer\x64\stampinf.exe" -f $infOut -d * -a amd64 -v 1.0.0.1
& "$KitRoot\bin\$SdkVer\x86\Inf2Cat.exe" /driver:$OutDir /os:10_x64
& 'C:\Programs\hydra\sign-driver.ps1' -DriverDir $OutDir

if (-not $Stage) {
    Write-Host ""
    Write-Host "Re-run with -Install -Stage to install and create the device." -ForegroundColor Cyan
    return
}

Write-Host ""
Write-Host "=== THE GATE ===" -ForegroundColor Cyan
Write-Host "Removing the shipped VDD package first -- two packages claiming the" -ForegroundColor Yellow
Write-Host "same hardware IDs is what broke the sample earlier today." -ForegroundColor Yellow

$e = (pnputil /enum-drivers | Out-String -Width 300) -split "`r?`n"
for ($i = 0; $i -lt $e.Count; $i++) {
    if ($e[$i] -match 'Original Name:\s+mttvdd\.inf') {
        $pub = ($e[$i-1] -replace '.*:\s+','')
        Write-Host "  removing $pub (shipped MttVDD)" -ForegroundColor Yellow
        pnputil /delete-driver $pub /uninstall *> $null
    }
}
Get-PnpDevice | Where-Object FriendlyName -match 'Virtual Display Driver' |
    ForEach-Object { & "$KitRoot\Tools\$SdkVer\x64\devgen.exe" /remove $_.InstanceId *> $null }

pnputil /add-driver $infOut /install
& "$KitRoot\Tools\$SdkVer\x64\devgen.exe" /add /hardwareid "Root\MttVDD"
Start-Sleep 8

Write-Host ""
Get-PnpDevice | Where-Object FriendlyName -match 'Virtual Display' |
    Select-Object FriendlyName, Status, InstanceId | Format-Table -AutoSize
Get-WinEvent -LogName 'Microsoft-Windows-DriverFrameworks-UserMode/Operational' -MaxEvents 4 |
    Select-Object TimeCreated, Id | Format-Table -AutoSize

Write-Host "Status OK, no event 2007  -> GATE PASSED. Proceed to MODE4-PLAN.md step 2." -ForegroundColor Green
Write-Host "Status Error, event 2007  -> the from-source build does not load though" -ForegroundColor Yellow
Write-Host "  the shipped binary does. STOP and find that difference first --" -ForegroundColor Yellow
Write-Host "  remote-session work on a driver that will not load is wasted." -ForegroundColor Yellow
Write-Host ""
Write-Host "Restore the shipped driver at any time:" -ForegroundColor DarkGray
Write-Host "  pnputil /add-driver C:\Programs\vdd\VirtualDisplayDriver\MttVDD.inf /install"
